#!/usr/bin/env bash
# Write a Bash script that displays the content
# of the file /etc/passwd

FILE="/etc/passwd"
while IFS=: read -r username _password userid _groupid _comment homedir _cmdshell
do
    echo "$username:$userid:$homedir"
done < $FILE
