#!/usr/bin/env bash
# This script gives you information about the school file.

FILE=*./school
if [ -e "$FILE" ]
then
    echo "school file exists"
    if [ ! -s "$FILE"]
    then
        echo "school file is empty"
    elif [ -s "$FILE" ]
    then
        echo "school file is not empty"
    elif [ -f "$FILE" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
